#!/usr/bin/env bash
set -euo pipefail

trap 'code=$?; echo 1>&2 ERROR!; exit $code' ERR

die() { code=$1; shift; echo 1>&2 "$@"; exit $code; }

prog=hello
prog=helloworld

cl65 -t vic20 $prog.c -o $prog.prg --mapfile map.txt

xvic +confirmexit -logfile xvic.log -autostartprgmode 1 $prog.prg
