#!/usr/bin/env bash
set -euo pipefail

trap 'code=$?; echo 1>&2 ERROR!; exit $code' ERR

die() { code=$1; shift; echo 1>&2 "$@"; exit $code; }

prog=hello
prog=cgetctest
prog=errdemo

target=vic20; emulator=xvic
#target=c64; emulator=x64
#target=plus4; emulator=xplus4

basedir=$(cd "$(dirname "$0")" && pwd -P)
cd "$basedir"
[[ -r cc65/Makefile ]] || git submodule update --init
make -C cc65/ -s -j 8

echo "----- Building $prog"
cc65/bin/cl65 -t $target $prog.c -o $prog.prg --mapfile $prog.map
$emulator -default +confirmexit -logfile $emulator.log \
    -autostartprgmode 1 $prog.prg
